global using Carter;
global using Mapster;
global using MediatR;
global using Marten;
global using FluentValidation;
global using CatalogAPI.Exceptions;
global using BuildingBlocks.CQRS;
global using BuildingBlocks.Behaviors;
global using CatalogAPI.Models;